name = "les_fdp"
author = "eladiouf"
version = "2.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b15ecdb6151c6d88da14a6eb627a8463e519f5555712085ffeca0af6e03a3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
