name = "les_fdp"
author = "eladiouf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57eb626af91a701b08a74ecb875f0c4f1b5d5d63844debd793a0b7edf9403d14"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
