name = "les_fdp"
author = "eladiouf"
version = "2.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57bcc235aa54c74e8eb42153fe25582d11c718818546c3fb741efae6b76353c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
